name: "Push Docker Image to AWS ECR"

inputs:
  BRANCH:
    description: "Specify which branch needs a push to fire the workflow"
    required: true

  AWS_ACCESS_KEY_ID:
    description: "Access Key required to login into AWS"
    required: true

  AWS_SECRET_ACCESS_KEY:
    description: "Secret Access Key required to login into AWS"
    required: true

  ECR_REGISTRY:
    description: "ECR Registry where the image is going to be pushed"
    required: true

  ECR_REPOSITORY:
    description: "ECR Repository where the image is going to be pushed"
    required: true

  DOCKERFILE_PATH:
    description: "Path where the Dockerfile is stored"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      shell: bash
      run: |
        docker build -t ${{ inputs.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:latest -f ${{ inputs.DOCKERFILE_PATH}} .
        docker push ${{ inputs.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:latest
