name: Deploy Staging

on:
  push:
    branches: 
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish Docker image into AWS ECR for Birdwoot
        uses: ./.github/actions/deployment/push-image-ecr
        with:
          BRANCH: develop
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID_STAGING }}
          ECR_REGISTRY: 823532849758.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: conversations/birdwoot/staging/birdwootmain
      
      - name: Build and publish Docker image into AWS ECR for Sidekiq
        uses: ./.github/actions/deployment/push-image-ecr
        with:
          BRANCH: develop
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID_STAGING }}
          ECR_REGISTRY: 823532849758.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: conversations/birdwoot/staging/sidekiq
